export const SheetData = [
    {
        id: 1,
        topic: 'Arrays - Matrix - Strings',
        img: "/Dsaz/Images/array.jpg",
        problems: [
            {
                id: 1,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Two sums",
                article: "https://www.geeksforgeeks.org/two-sum-problem/",
                leetcode: "https://leetcode.com/problems/two-sum/",
                gfg: "https://www.geeksforgeeks.org/two-sum/",
            },
            {
                id: 2,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Three sums",
                article: "https://www.geeksforgeeks.org/find-triplets-array-whose-sum-equal-zero/",
                leetcode: "https://leetcode.com/problems/3sum/",
                gfg: "https://www.geeksforgeeks.org/find-triplets-array-whose-sum-equal-zero/",
            },
            {
                id: 3,
                status: "pending",
                isSolved: false,
                type: "Medium",
                question: "Four sums",
                article: "https://www.geeksforgeeks.org/find-four-elements-that-sum-to-a-given-value-set-2/",
                leetcode: "https://leetcode.com/problems/4sum/",
                gfg: "https://www.geeksforgeeks.org/find-four-elements-that-sum-to-a-given-value-set-2/",
            },
            {
                id: 4,
                status: "pending",
                isSolved: false,
                type: "Medium",
                question: "Maximum subarray",
                article: "https://www.geeksforgeeks.org/largest-sum-contiguous-subarray/",
                leetcode: "https://leetcode.com/problems/maximum-subarray/",
                gfg: "https://www.geeksforgeeks.org/largest-sum-contiguous-subarray/",
            },
            {
                id: 5,
                status: "pending",
                isSolved: false,
                type: "Medium",
                question: "Maximum product subarray",
                article: "https://www.geeksforgeeks.org/maximum-product-subarray/",
                leetcode: "https://leetcode.com/problems/maximum-product-subarray/",
                gfg: "https://www.geeksforgeeks.org/maximum-product-subarray/",
            },
            {
                id: 6,
                status: "pending",
                isSolved: false,
                type: "Medium",
                question: "Find minimum in rotated sorted array",
                article: "https://www.geeksforgeeks.org/find-minimum-element-in-a-sorted-and-rotated-array/",
                leetcode: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
                gfg: "https://www.geeksforgeeks.org/find-minimum-element-in-a-sorted-and-rotated-array/",
            },
            {
                id: 7,
                status: "pending",
                isSolved: false,
                type: "Hard",
                question: "Search in rotated sorted array",
                article: "https://www.geeksforgeeks.org/search-an-element-in-a-sorted-and-pivoted-array/",
                leetcode: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
                gfg: "https://www.geeksforgeeks.org/search-an-element-in-a-sorted-and-pivoted-array/",
            },
            {
                id: 8,
                status: "pending",
                isSolved: false,
                type: "Hard",
                question: "Climbing stairs",
                article: "https://www.geeksforgeeks.org/count-ways-reach-nth-stair/",
                leetcode: "https://leetcode.com/problems/climbing-stairs/",
                gfg: "https://www.geeksforgeeks.org/count-ways-reach-nth-stair/",
            },
        ],
        Easy: 2,
        Medium: 4,
        Hard: 2,
        overview: "Lorem ipsum dolor sit amet, consectetur adipisicingelit. Saepe voluptates pariatur sed atque repellat laudantium, ut assumenda excepturi",
        solved: 0,
        totalQues: 8
    },
    {
        id: 2,
        topic: 'PrefixSum - SuffixSum - Intervals',
        img: "/Dsaz/Images/Lc-2.png",
        problems: [
            {
                id: 1,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "prefix sum",
                article: "https://www.geeksforgeeks.org/two-sum-problem/",
                leetcode: "https://leetcode.com/problems/two-sum/",
                gfg: "https://www.geeksforgeeks.org/two-sum/",
            },
            {
                id: 2,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Three sums",
                article: "https://www.geeksforgeeks.org/find-triplets-array-whose-sum-equal-zero/",
                leetcode: "https://leetcode.com/problems/3sum/",
                gfg: "https://www.geeksforgeeks.org/find-triplets-array-whose-sum-equal-zero/",
            },
            {
                id: 3,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Four sums",
                article: "https://www.geeksforgeeks.org/find-four-elements-that-sum-to-a-given-value-set-2/",
                leetcode: "https://leetcode.com/problems/4sum/",
                gfg: "https://www.geeksforgeeks.org/find-four-elements-that-sum-to-a-given-value-set-2/",
            },
            {
                id: 4,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Maximum subarray",
                article: "https://www.geeksforgeeks.org/largest-sum-contiguous-subarray/",
                leetcode: "https://leetcode.com/problems/maximum-subarray/",
                gfg: "https://www.geeksforgeeks.org/largest-sum-contiguous-subarray/",
            },
            {
                id: 5,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Maximum product subarray",
                article: "https://www.geeksforgeeks.org/maximum-product-subarray/",
                leetcode: "https://leetcode.com/problems/maximum-product-subarray/",
                gfg: "https://www.geeksforgeeks.org/maximum-product-subarray/",
            },
            {
                id: 6,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Find minimum in rotated sorted array",
                article: "https://www.geeksforgeeks.org/find-minimum-element-in-a-sorted-and-rotated-array/",
                leetcode: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
                gfg: "https://www.geeksforgeeks.org/find-minimum-element-in-a-sorted-and-rotated-array/",
            },
            {
                id: 7,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Search in rotated sorted array",
                article: "https://www.geeksforgeeks.org/search-an-element-in-a-sorted-and-pivoted-array/",
                leetcode: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
                gfg: "https://www.geeksforgeeks.org/search-an-element-in-a-sorted-and-pivoted-array/",
            },
            {
                id: 8,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Climbing stairs",
                article: "https://www.geeksforgeeks.org/count-ways-reach-nth-stair/",
                leetcode: "https://leetcode.com/problems/climbing-stairs/",
                gfg: "https://www.geeksforgeeks.org/count-ways-reach-nth-stair/",
            },
        ],
        Easy: 3,
        Medium: 5,
        Hard: 2,
        overview: "Lorem ipsum dolor sit amet, consectetur adipisicingelit. Saepe voluptates pariatur sed atque repellat laudantium, ut assumenda excepturi",
        solved: 5,
        totalQues: 10
    },
    {
        id: 3,
        topic: 'Searching & Sorting',
        img: "/Dsaz/Images/Lc-3.png",
        problems: [
            {
                id: 1,
                status: "pending",
                question: "Two sums",
                isSolved: false,
                type: "Easy",
                article: "https://www.geeksforgeeks.org/two-sum-problem/",
                leetcode: "https://leetcode.com/problems/two-sum/",
                gfg: "https://www.geeksforgeeks.org/two-sum/",
            },
            {
                id: 2,
                status: "pending",
                question: "Three sums",
                isSolved: false,
                type: "Easy",
                article: "https://www.geeksforgeeks.org/find-triplets-array-whose-sum-equal-zero/",
                leetcode: "https://leetcode.com/problems/3sum/",
                gfg: "https://www.geeksforgeeks.org/find-triplets-array-whose-sum-equal-zero/",
            },
            {
                id: 3,
                status: "pending",
                question: "Four sums",
                isSolved: false,
                type: "Easy",
                article: "https://www.geeksforgeeks.org/find-four-elements-that-sum-to-a-given-value-set-2/",
                leetcode: "https://leetcode.com/problems/4sum/",
                gfg: "https://www.geeksforgeeks.org/find-four-elements-that-sum-to-a-given-value-set-2/",
            },
            {
                id: 4,
                status: "pending",
                question: "Maximum subarray",
                isSolved: false,
                type: "Easy",
                article: "https://www.geeksforgeeks.org/largest-sum-contiguous-subarray/",
                leetcode: "https://leetcode.com/problems/maximum-subarray/",
                gfg: "https://www.geeksforgeeks.org/largest-sum-contiguous-subarray/",
            },
            {
                id: 5,
                status: "pending",
                question: "Maximum product subarray",
                isSolved: false,
                type: "Easy",
                article: "https://www.geeksforgeeks.org/maximum-product-subarray/",
                leetcode: "https://leetcode.com/problems/maximum-product-subarray/",
                gfg: "https://www.geeksforgeeks.org/maximum-product-subarray/",
            },
            {
                id: 6,
                status: "pending",
                question: "Find minimum in rotated sorted array",
                isSolved: false,
                type: "Easy",
                article: "https://www.geeksforgeeks.org/find-minimum-element-in-a-sorted-and-rotated-array/",
                leetcode: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
                gfg: "https://www.geeksforgeeks.org/find-minimum-element-in-a-sorted-and-rotated-array/",
            },
            {
                id: 7,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Search in rotated sorted array",
                article: "https://www.geeksforgeeks.org/search-an-element-in-a-sorted-and-pivoted-array/",
                leetcode: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
                gfg: "https://www.geeksforgeeks.org/search-an-element-in-a-sorted-and-pivoted-array/",
            },
            {
                id: 8,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Climbing stairs",
                article: "https://www.geeksforgeeks.org/count-ways-reach-nth-stair/",
                leetcode: "https://leetcode.com/problems/climbing-stairs/",
                gfg: "https://www.geeksforgeeks.org/count-ways-reach-nth-stair/",
            },
        ],
        Easy: 3,
        Medium: 5,
        Hard: 2,
        overview: "Lorem ipsum dolor sit amet, consectetur adipisicingelit. Saepe voluptates pariatur sed atque repellat laudantium, ut assumenda excepturi",
        solved: 7,
        totalQues: 15
    },
    {
        id: 4,
        topic: 'Binary Search',
        img: "/Dsaz/Images/binary.webp",
        problems: [
            {
                id: 1,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Two sums",
                article: "https://www.geeksforgeeks.org/two-sum-problem/",
                leetcode: "https://leetcode.com/problems/two-sum/",
                gfg: "https://www.geeksforgeeks.org/two-sum/",
            },
            {
                id: 2,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Three sums",
                article: "https://www.geeksforgeeks.org/find-triplets-array-whose-sum-equal-zero/",
                leetcode: "https://leetcode.com/problems/3sum/",
                gfg: "https://www.geeksforgeeks.org/find-triplets-array-whose-sum-equal-zero/",
            },
            {
                id: 3,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Four sums",
                article: "https://www.geeksforgeeks.org/find-four-elements-that-sum-to-a-given-value-set-2/",
                leetcode: "https://leetcode.com/problems/4sum/",
                gfg: "https://www.geeksforgeeks.org/find-four-elements-that-sum-to-a-given-value-set-2/",
            },
            {
                id: 4,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Maximum subarray",
                article: "https://www.geeksforgeeks.org/largest-sum-contiguous-subarray/",
                leetcode: "https://leetcode.com/problems/maximum-subarray/",
                gfg: "https://www.geeksforgeeks.org/largest-sum-contiguous-subarray/",
            },
            {
                id: 5,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Maximum product subarray",
                article: "https://www.geeksforgeeks.org/maximum-product-subarray/",
                leetcode: "https://leetcode.com/problems/maximum-product-subarray/",
                gfg: "https://www.geeksforgeeks.org/maximum-product-subarray/",
            },
            {
                id: 6,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Find minimum in rotated sorted array",
                article: "https://www.geeksforgeeks.org/find-minimum-element-in-a-sorted-and-rotated-array/",
                leetcode: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
                gfg: "https://www.geeksforgeeks.org/find-minimum-element-in-a-sorted-and-rotated-array/",
            },
            {
                id: 7,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Search in rotated sorted array",
                article: "https://www.geeksforgeeks.org/search-an-element-in-a-sorted-and-pivoted-array/",
                leetcode: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
                gfg: "https://www.geeksforgeeks.org/search-an-element-in-a-sorted-and-pivoted-array/",
            },
            {
                id: 8,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Climbing stairs",
                article: "https://www.geeksforgeeks.org/count-ways-reach-nth-stair/",
                leetcode: "https://leetcode.com/problems/climbing-stairs/",
                gfg: "https://www.geeksforgeeks.org/count-ways-reach-nth-stair/",
            },
        ],
        Easy: 3,
        Medium: 5,
        Hard: 2,
        overview: "Lorem ipsum dolor sit amet, consectetur adipisicingelit. Saepe voluptates pariatur sed atque repellat laudantium, ut assumenda excepturi",
        solved: 5,
        totalQues: 10
    },
    {
        id: 5,
        topic: 'Two Pointers - Sliding Window',
        img: "/Dsaz/Images/array.jpg",
        problems: [
            {
                id: 1,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Two sums",
                article: "https://www.geeksforgeeks.org/two-sum-problem/",
                leetcode: "https://leetcode.com/problems/two-sum/",
                gfg: "https://www.geeksforgeeks.org/two-sum/",
            },
            {
                id: 2,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Three sums",
                article: "https://www.geeksforgeeks.org/find-triplets-array-whose-sum-equal-zero/",
                leetcode: "https://leetcode.com/problems/3sum/",
                gfg: "https://www.geeksforgeeks.org/find-triplets-array-whose-sum-equal-zero/",
            },
            {
                id: 3,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Four sums",
                article: "https://www.geeksforgeeks.org/find-four-elements-that-sum-to-a-given-value-set-2/",
                leetcode: "https://leetcode.com/problems/4sum/",
                gfg: "https://www.geeksforgeeks.org/find-four-elements-that-sum-to-a-given-value-set-2/",
            },
            {
                id: 4,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Maximum subarray",
                article: "https://www.geeksforgeeks.org/largest-sum-contiguous-subarray/",
                leetcode: "https://leetcode.com/problems/maximum-subarray/",
                gfg: "https://www.geeksforgeeks.org/largest-sum-contiguous-subarray/",
            },
            {
                id: 5,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Maximum product subarray",
                article: "https://www.geeksforgeeks.org/maximum-product-subarray/",
                leetcode: "https://leetcode.com/problems/maximum-product-subarray/",
                gfg: "https://www.geeksforgeeks.org/maximum-product-subarray/",
            },
            {
                id: 6,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Find minimum in rotated sorted array",
                article: "https://www.geeksforgeeks.org/find-minimum-element-in-a-sorted-and-rotated-array/",
                leetcode: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
                gfg: "https://www.geeksforgeeks.org/find-minimum-element-in-a-sorted-and-rotated-array/",
            },
            {
                id: 7,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Search in rotated sorted array",
                article: "https://www.geeksforgeeks.org/search-an-element-in-a-sorted-and-pivoted-array/",
                leetcode: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
                gfg: "https://www.geeksforgeeks.org/search-an-element-in-a-sorted-and-pivoted-array/",
            },
            {
                id: 8,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Climbing stairs",
                article: "https://www.geeksforgeeks.org/count-ways-reach-nth-stair/",
                leetcode: "https://leetcode.com/problems/climbing-stairs/",
                gfg: "https://www.geeksforgeeks.org/count-ways-reach-nth-stair/",
            },
        ],
        Easy: 3,
        Medium: 5,
        Hard: 2,
        overview: "Lorem ipsum dolor sit amet, consectetur adipisicingelit. Saepe voluptates pariatur sed atque repellat laudantium, ut assumenda excepturi",
        solved: 5,
        totalQues: 10
    },
    {
        id: 6,
        topic: 'Linked List',
        img: "/Dsaz/Images/linked list.jpg",
        problems: [
            {
                id: 1,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Two sums",
                article: "https://www.geeksforgeeks.org/two-sum-problem/",
                leetcode: "https://leetcode.com/problems/two-sum/",
                gfg: "https://www.geeksforgeeks.org/two-sum/",
            },
            {
                id: 2,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Three sums",
                article: "https://www.geeksforgeeks.org/find-triplets-array-whose-sum-equal-zero/",
                leetcode: "https://leetcode.com/problems/3sum/",
                gfg: "https://www.geeksforgeeks.org/find-triplets-array-whose-sum-equal-zero/",
            },
            {
                id: 3,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Four sums",
                article: "https://www.geeksforgeeks.org/find-four-elements-that-sum-to-a-given-value-set-2/",
                leetcode: "https://leetcode.com/problems/4sum/",
                gfg: "https://www.geeksforgeeks.org/find-four-elements-that-sum-to-a-given-value-set-2/",
            },
            {
                id: 4,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Maximum subarray",
                article: "https://www.geeksforgeeks.org/largest-sum-contiguous-subarray/",
                leetcode: "https://leetcode.com/problems/maximum-subarray/",
                gfg: "https://www.geeksforgeeks.org/largest-sum-contiguous-subarray/",
            },
            {
                id: 5,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Maximum product subarray",
                article: "https://www.geeksforgeeks.org/maximum-product-subarray/",
                leetcode: "https://leetcode.com/problems/maximum-product-subarray/",
                gfg: "https://www.geeksforgeeks.org/maximum-product-subarray/",
            },
            {
                id: 6,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Find minimum in rotated sorted array",
                article: "https://www.geeksforgeeks.org/find-minimum-element-in-a-sorted-and-rotated-array/",
                leetcode: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
                gfg: "https://www.geeksforgeeks.org/find-minimum-element-in-a-sorted-and-rotated-array/",
            },
            {
                id: 7,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Search in rotated sorted array",
                article: "https://www.geeksforgeeks.org/search-an-element-in-a-sorted-and-pivoted-array/",
                leetcode: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
                gfg: "https://www.geeksforgeeks.org/search-an-element-in-a-sorted-and-pivoted-array/",
            },
            {
                id: 8,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Climbing stairs",
                article: "https://www.geeksforgeeks.org/count-ways-reach-nth-stair/",
                leetcode: "https://leetcode.com/problems/climbing-stairs/",
                gfg: "https://www.geeksforgeeks.org/count-ways-reach-nth-stair/",
            },
        ],
        Easy: 3,
        Medium: 5,
        Hard: 2,
        overview: "Lorem ipsum dolor sit amet, consectetur adipisicingelit. Saepe voluptates pariatur sed atque repellat laudantium, ut assumenda excepturi",
        solved: 5,
        totalQues: 10
    },
    {
        id: 7,
        topic: 'Stacks & Queues',
        img: "/Dsaz/Images/Stack.png",
        problems: [
            {
                id: 1,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Two sums",
                article: "https://www.geeksforgeeks.org/two-sum-problem/",
                leetcode: "https://leetcode.com/problems/two-sum/",
                gfg: "https://www.geeksforgeeks.org/two-sum/",
            },
            {
                id: 2,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Three sums",
                article: "https://www.geeksforgeeks.org/find-triplets-array-whose-sum-equal-zero/",
                leetcode: "https://leetcode.com/problems/3sum/",
                gfg: "https://www.geeksforgeeks.org/find-triplets-array-whose-sum-equal-zero/",
            },
            {
                id: 3,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Four sums",
                article: "https://www.geeksforgeeks.org/find-four-elements-that-sum-to-a-given-value-set-2/",
                leetcode: "https://leetcode.com/problems/4sum/",
                gfg: "https://www.geeksforgeeks.org/find-four-elements-that-sum-to-a-given-value-set-2/",
            },
            {
                id: 4,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Maximum subarray",
                article: "https://www.geeksforgeeks.org/largest-sum-contiguous-subarray/",
                leetcode: "https://leetcode.com/problems/maximum-subarray/",
                gfg: "https://www.geeksforgeeks.org/largest-sum-contiguous-subarray/",
            },
            {
                id: 5,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Maximum product subarray",
                article: "https://www.geeksforgeeks.org/maximum-product-subarray/",
                leetcode: "https://leetcode.com/problems/maximum-product-subarray/",
                gfg: "https://www.geeksforgeeks.org/maximum-product-subarray/",
            },
            {
                id: 6,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Find minimum in rotated sorted array",
                article: "https://www.geeksforgeeks.org/find-minimum-element-in-a-sorted-and-rotated-array/",
                leetcode: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
                gfg: "https://www.geeksforgeeks.org/find-minimum-element-in-a-sorted-and-rotated-array/",
            },
            {
                id: 7,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Search in rotated sorted array",
                article: "https://www.geeksforgeeks.org/search-an-element-in-a-sorted-and-pivoted-array/",
                leetcode: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
                gfg: "https://www.geeksforgeeks.org/search-an-element-in-a-sorted-and-pivoted-array/",
            },
            {
                id: 8,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Climbing stairs",
                article: "https://www.geeksforgeeks.org/count-ways-reach-nth-stair/",
                leetcode: "https://leetcode.com/problems/climbing-stairs/",
                gfg: "https://www.geeksforgeeks.org/count-ways-reach-nth-stair/",
            },
        ],
        Easy: 3,
        Medium: 5,
        Hard: 2,
        overview: "Lorem ipsum dolor sit amet, consectetur adipisicingelit. Saepe voluptates pariatur sed atque repellat laudantium, ut assumenda excepturi",
        solved: 5,
        totalQues: 10
    },
    {
        id: 8,
        topic: 'Bit Manipulation - Bitmasking',
        img: "/Dsaz/Images/binary1.jpg",
        problems: [
            {
                id: 1,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Two sums",
                article: "https://www.geeksforgeeks.org/two-sum-problem/",
                leetcode: "https://leetcode.com/problems/two-sum/",
                gfg: "https://www.geeksforgeeks.org/two-sum/",
            },
            {
                id: 2,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Three sums",
                article: "https://www.geeksforgeeks.org/find-triplets-array-whose-sum-equal-zero/",
                leetcode: "https://leetcode.com/problems/3sum/",
                gfg: "https://www.geeksforgeeks.org/find-triplets-array-whose-sum-equal-zero/",
            },
            {
                id: 3,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Four sums",
                article: "https://www.geeksforgeeks.org/find-four-elements-that-sum-to-a-given-value-set-2/",
                leetcode: "https://leetcode.com/problems/4sum/",
                gfg: "https://www.geeksforgeeks.org/find-four-elements-that-sum-to-a-given-value-set-2/",
            },
            {
                id: 4,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Maximum subarray",
                article: "https://www.geeksforgeeks.org/largest-sum-contiguous-subarray/",
                leetcode: "https://leetcode.com/problems/maximum-subarray/",
                gfg: "https://www.geeksforgeeks.org/largest-sum-contiguous-subarray/",
            },
            {
                id: 5,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Maximum product subarray",
                article: "https://www.geeksforgeeks.org/maximum-product-subarray/",
                leetcode: "https://leetcode.com/problems/maximum-product-subarray/",
                gfg: "https://www.geeksforgeeks.org/maximum-product-subarray/",
            },
            {
                id: 6,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Find minimum in rotated sorted array",
                article: "https://www.geeksforgeeks.org/find-minimum-element-in-a-sorted-and-rotated-array/",
                leetcode: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
                gfg: "https://www.geeksforgeeks.org/find-minimum-element-in-a-sorted-and-rotated-array/",
            },
            {
                id: 7,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Search in rotated sorted array",
                article: "https://www.geeksforgeeks.org/search-an-element-in-a-sorted-and-pivoted-array/",
                leetcode: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
                gfg: "https://www.geeksforgeeks.org/search-an-element-in-a-sorted-and-pivoted-array/",
            },
            {
                id: 8,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Climbing stairs",
                article: "https://www.geeksforgeeks.org/count-ways-reach-nth-stair/",
                leetcode: "https://leetcode.com/problems/climbing-stairs/",
                gfg: "https://www.geeksforgeeks.org/count-ways-reach-nth-stair/",
            },
        ],
        Easy: 3,
        Medium: 5,
        Hard: 2,
        overview: "Lorem ipsum dolor sit amet, consectetur adipisicingelit. Saepe voluptates pariatur sed atque repellat laudantium, ut assumenda excepturi",
        solved: 5,
        totalQues: 10
    },
    {
        id: 9,
        topic: 'Recursion & Backtracking',
        img: "/Dsaz/Images/recursion.jpeg",
        problems: [
            {
                id: 1,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Two sums",
                article: "https://www.geeksforgeeks.org/two-sum-problem/",
                leetcode: "https://leetcode.com/problems/two-sum/",
                gfg: "https://www.geeksforgeeks.org/two-sum/",
            },
            {
                id: 2,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Three sums",
                article: "https://www.geeksforgeeks.org/find-triplets-array-whose-sum-equal-zero/",
                leetcode: "https://leetcode.com/problems/3sum/",
                gfg: "https://www.geeksforgeeks.org/find-triplets-array-whose-sum-equal-zero/",
            },
            {
                id: 3,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Four sums",
                article: "https://www.geeksforgeeks.org/find-four-elements-that-sum-to-a-given-value-set-2/",
                leetcode: "https://leetcode.com/problems/4sum/",
                gfg: "https://www.geeksforgeeks.org/find-four-elements-that-sum-to-a-given-value-set-2/",
            },
            {
                id: 4,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Maximum subarray",
                article: "https://www.geeksforgeeks.org/largest-sum-contiguous-subarray/",
                leetcode: "https://leetcode.com/problems/maximum-subarray/",
                gfg: "https://www.geeksforgeeks.org/largest-sum-contiguous-subarray/",
            },
            {
                id: 5,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Maximum product subarray",
                article: "https://www.geeksforgeeks.org/maximum-product-subarray/",
                leetcode: "https://leetcode.com/problems/maximum-product-subarray/",
                gfg: "https://www.geeksforgeeks.org/maximum-product-subarray/",
            },
            {
                id: 6,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Find minimum in rotated sorted array",
                article: "https://www.geeksforgeeks.org/find-minimum-element-in-a-sorted-and-rotated-array/",
                leetcode: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
                gfg: "https://www.geeksforgeeks.org/find-minimum-element-in-a-sorted-and-rotated-array/",
            },
            {
                id: 7,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Search in rotated sorted array",
                article: "https://www.geeksforgeeks.org/search-an-element-in-a-sorted-and-pivoted-array/",
                leetcode: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
                gfg: "https://www.geeksforgeeks.org/search-an-element-in-a-sorted-and-pivoted-array/",
            },
            {
                id: 8,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Climbing stairs",
                article: "https://www.geeksforgeeks.org/count-ways-reach-nth-stair/",
                leetcode: "https://leetcode.com/problems/climbing-stairs/",
                gfg: "https://www.geeksforgeeks.org/count-ways-reach-nth-stair/",
            },
        ],
        Easy: 3,
        Medium: 5,
        Hard: 2,
        overview: "Lorem ipsum dolor sit amet, consectetur adipisicingelit. Saepe voluptates pariatur sed atque repellat laudantium, ut assumenda excepturi",
        solved: 5,
        totalQues: 10
    },
    {
        id: 10,
        topic: 'Tree',
        img: "/Dsaz/Images/Lc-4.png",
        problems: [
            {
                id: 1,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Two sums",
                article: "https://www.geeksforgeeks.org/two-sum-problem/",
                leetcode: "https://leetcode.com/problems/two-sum/",
                gfg: "https://www.geeksforgeeks.org/two-sum/",
            },
            {
                id: 2,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Three sums",
                article: "https://www.geeksforgeeks.org/find-triplets-array-whose-sum-equal-zero/",
                leetcode: "https://leetcode.com/problems/3sum/",
                gfg: "https://www.geeksforgeeks.org/find-triplets-array-whose-sum-equal-zero/",
            },
            {
                id: 3,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Four sums",
                article: "https://www.geeksforgeeks.org/find-four-elements-that-sum-to-a-given-value-set-2/",
                leetcode: "https://leetcode.com/problems/4sum/",
                gfg: "https://www.geeksforgeeks.org/find-four-elements-that-sum-to-a-given-value-set-2/",
            },
            {
                id: 4,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Maximum subarray",
                article: "https://www.geeksforgeeks.org/largest-sum-contiguous-subarray/",
                leetcode: "https://leetcode.com/problems/maximum-subarray/",
                gfg: "https://www.geeksforgeeks.org/largest-sum-contiguous-subarray/",
            },
            {
                id: 5,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Maximum product subarray",
                article: "https://www.geeksforgeeks.org/maximum-product-subarray/",
                leetcode: "https://leetcode.com/problems/maximum-product-subarray/",
                gfg: "https://www.geeksforgeeks.org/maximum-product-subarray/",
            },
            {
                id: 6,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Find minimum in rotated sorted array",
                article: "https://www.geeksforgeeks.org/find-minimum-element-in-a-sorted-and-rotated-array/",
                leetcode: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
                gfg: "https://www.geeksforgeeks.org/find-minimum-element-in-a-sorted-and-rotated-array/",
            },
            {
                id: 7,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Search in rotated sorted array",
                article: "https://www.geeksforgeeks.org/search-an-element-in-a-sorted-and-pivoted-array/",
                leetcode: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
                gfg: "https://www.geeksforgeeks.org/search-an-element-in-a-sorted-and-pivoted-array/",
            },
            {
                id: 8,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Climbing stairs",
                article: "https://www.geeksforgeeks.org/count-ways-reach-nth-stair/",
                leetcode: "https://leetcode.com/problems/climbing-stairs/",
                gfg: "https://www.geeksforgeeks.org/count-ways-reach-nth-stair/",
            },
        ],
        Easy: 3,
        Medium: 5,
        Hard: 2,
        overview: "Lorem ipsum dolor sit amet, consectetur adipisicingelit. Saepe voluptates pariatur sed atque repellat laudantium, ut assumenda excepturi",
        solved: 5,
        totalQues: 10
    },
    {
        id: 11,
        topic: 'Heaps - Priority Queue',
        img: "/Dsaz/Images/queue.jpg",
        problems: [
            {
                id: 1,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Two sums",
                article: "https://www.geeksforgeeks.org/two-sum-problem/",
                leetcode: "https://leetcode.com/problems/two-sum/",
                gfg: "https://www.geeksforgeeks.org/two-sum/",
            },
            {
                id: 2,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Three sums",
                article: "https://www.geeksforgeeks.org/find-triplets-array-whose-sum-equal-zero/",
                leetcode: "https://leetcode.com/problems/3sum/",
                gfg: "https://www.geeksforgeeks.org/find-triplets-array-whose-sum-equal-zero/",
            },
            {
                id: 3,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Four sums",
                article: "https://www.geeksforgeeks.org/find-four-elements-that-sum-to-a-given-value-set-2/",
                leetcode: "https://leetcode.com/problems/4sum/",
                gfg: "https://www.geeksforgeeks.org/find-four-elements-that-sum-to-a-given-value-set-2/",
            },
            {
                id: 4,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Maximum subarray",
                article: "https://www.geeksforgeeks.org/largest-sum-contiguous-subarray/",
                leetcode: "https://leetcode.com/problems/maximum-subarray/",
                gfg: "https://www.geeksforgeeks.org/largest-sum-contiguous-subarray/",
            },
            {
                id: 5,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Maximum product subarray",
                article: "https://www.geeksforgeeks.org/maximum-product-subarray/",
                leetcode: "https://leetcode.com/problems/maximum-product-subarray/",
                gfg: "https://www.geeksforgeeks.org/maximum-product-subarray/",
            },
            {
                id: 6,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Find minimum in rotated sorted array",
                article: "https://www.geeksforgeeks.org/find-minimum-element-in-a-sorted-and-rotated-array/",
                leetcode: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
                gfg: "https://www.geeksforgeeks.org/find-minimum-element-in-a-sorted-and-rotated-array/",
            },
            {
                id: 7,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Search in rotated sorted array",
                article: "https://www.geeksforgeeks.org/search-an-element-in-a-sorted-and-pivoted-array/",
                leetcode: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
                gfg: "https://www.geeksforgeeks.org/search-an-element-in-a-sorted-and-pivoted-array/",
            },
            {
                id: 8,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Climbing stairs",
                article: "https://www.geeksforgeeks.org/count-ways-reach-nth-stair/",
                leetcode: "https://leetcode.com/problems/climbing-stairs/",
                gfg: "https://www.geeksforgeeks.org/count-ways-reach-nth-stair/",
            },
        ],
        Easy: 3,
        Medium: 5,
        Hard: 2,
        overview: "Lorem ipsum dolor sit amet, consectetur adipisicingelit. Saepe voluptates pariatur sed atque repellat laudantium, ut assumenda excepturi",
        solved: 5,
        totalQues: 10
    },
    {
        id: 12,
        topic: 'Greedy',
        img: "/Dsaz/Images/Lc-2.png",
        problems: [
            {
                id: 1,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Two sums",
                article: "https://www.geeksforgeeks.org/two-sum-problem/",
                leetcode: "https://leetcode.com/problems/two-sum/",
                gfg: "https://www.geeksforgeeks.org/two-sum/",
            },
            {
                id: 2,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Three sums",
                article: "https://www.geeksforgeeks.org/find-triplets-array-whose-sum-equal-zero/",
                leetcode: "https://leetcode.com/problems/3sum/",
                gfg: "https://www.geeksforgeeks.org/find-triplets-array-whose-sum-equal-zero/",
            },
            {
                id: 3,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Four sums",
                article: "https://www.geeksforgeeks.org/find-four-elements-that-sum-to-a-given-value-set-2/",
                leetcode: "https://leetcode.com/problems/4sum/",
                gfg: "https://www.geeksforgeeks.org/find-four-elements-that-sum-to-a-given-value-set-2/",
            },
            {
                id: 4,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Maximum subarray",
                article: "https://www.geeksforgeeks.org/largest-sum-contiguous-subarray/",
                leetcode: "https://leetcode.com/problems/maximum-subarray/",
                gfg: "https://www.geeksforgeeks.org/largest-sum-contiguous-subarray/",
            },
            {
                id: 5,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Maximum product subarray",
                article: "https://www.geeksforgeeks.org/maximum-product-subarray/",
                leetcode: "https://leetcode.com/problems/maximum-product-subarray/",
                gfg: "https://www.geeksforgeeks.org/maximum-product-subarray/",
            },
            {
                id: 6,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Find minimum in rotated sorted array",
                article: "https://www.geeksforgeeks.org/find-minimum-element-in-a-sorted-and-rotated-array/",
                leetcode: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
                gfg: "https://www.geeksforgeeks.org/find-minimum-element-in-a-sorted-and-rotated-array/",
            },
            {
                id: 7,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Search in rotated sorted array",
                article: "https://www.geeksforgeeks.org/search-an-element-in-a-sorted-and-pivoted-array/",
                leetcode: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
                gfg: "https://www.geeksforgeeks.org/search-an-element-in-a-sorted-and-pivoted-array/",
            },
            {
                id: 8,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Climbing stairs",
                article: "https://www.geeksforgeeks.org/count-ways-reach-nth-stair/",
                leetcode: "https://leetcode.com/problems/climbing-stairs/",
                gfg: "https://www.geeksforgeeks.org/count-ways-reach-nth-stair/",
            },
        ],
        Easy: 3,
        Medium: 5,
        Hard: 2,
        overview: "Lorem ipsum dolor sit amet, consectetur adipisicingelit. Saepe voluptates pariatur sed atque repellat laudantium, ut assumenda excepturi",
        solved: 5,
        totalQues: 10
    },
    {
        id: 13,
        topic: 'Hashing',
        img: "/Dsaz/Images/Lc-3.png",
        problems: [
            {
                id: 1,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Two sums",
                article: "https://www.geeksforgeeks.org/two-sum-problem/",
                leetcode: "https://leetcode.com/problems/two-sum/",
                gfg: "https://www.geeksforgeeks.org/two-sum/",
            },
            {
                id: 2,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Three sums",
                article: "https://www.geeksforgeeks.org/find-triplets-array-whose-sum-equal-zero/",
                leetcode: "https://leetcode.com/problems/3sum/",
                gfg: "https://www.geeksforgeeks.org/find-triplets-array-whose-sum-equal-zero/",
            },
            {
                id: 3,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Four sums",
                article: "https://www.geeksforgeeks.org/find-four-elements-that-sum-to-a-given-value-set-2/",
                leetcode: "https://leetcode.com/problems/4sum/",
                gfg: "https://www.geeksforgeeks.org/find-four-elements-that-sum-to-a-given-value-set-2/",
            },
            {
                id: 4,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Maximum subarray",
                article: "https://www.geeksforgeeks.org/largest-sum-contiguous-subarray/",
                leetcode: "https://leetcode.com/problems/maximum-subarray/",
                gfg: "https://www.geeksforgeeks.org/largest-sum-contiguous-subarray/",
            },
            {
                id: 5,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Maximum product subarray",
                article: "https://www.geeksforgeeks.org/maximum-product-subarray/",
                leetcode: "https://leetcode.com/problems/maximum-product-subarray/",
                gfg: "https://www.geeksforgeeks.org/maximum-product-subarray/",
            },
            {
                id: 6,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Find minimum in rotated sorted array",
                article: "https://www.geeksforgeeks.org/find-minimum-element-in-a-sorted-and-rotated-array/",
                leetcode: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
                gfg: "https://www.geeksforgeeks.org/find-minimum-element-in-a-sorted-and-rotated-array/",
            },
            {
                id: 7,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Search in rotated sorted array",
                article: "https://www.geeksforgeeks.org/search-an-element-in-a-sorted-and-pivoted-array/",
                leetcode: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
                gfg: "https://www.geeksforgeeks.org/search-an-element-in-a-sorted-and-pivoted-array/",
            },
            {
                id: 8,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Climbing stairs",
                article: "https://www.geeksforgeeks.org/count-ways-reach-nth-stair/",
                leetcode: "https://leetcode.com/problems/climbing-stairs/",
                gfg: "https://www.geeksforgeeks.org/count-ways-reach-nth-stair/",
            },
        ],
        Easy: 3,
        Medium: 5,
        Hard: 2,
        overview: "Lorem ipsum dolor sit amet, consectetur adipisicingelit. Saepe voluptates pariatur sed atque repellat laudantium, ut assumenda excepturi",
        solved: 5,
        totalQues: 10
    },
    {
        id: 14,
        topic: 'Graphs',
        img: "/Dsaz/Images/graph2.jpg",
        problems: [
            {
                id: 1,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Two sums",
                article: "https://www.geeksforgeeks.org/two-sum-problem/",
                leetcode: "https://leetcode.com/problems/two-sum/",
                gfg: "https://www.geeksforgeeks.org/two-sum/",
            },
            {
                id: 2,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Three sums",
                article: "https://www.geeksforgeeks.org/find-triplets-array-whose-sum-equal-zero/",
                leetcode: "https://leetcode.com/problems/3sum/",
                gfg: "https://www.geeksforgeeks.org/find-triplets-array-whose-sum-equal-zero/",
            },
            {
                id: 3,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Four sums",
                article: "https://www.geeksforgeeks.org/find-four-elements-that-sum-to-a-given-value-set-2/",
                leetcode: "https://leetcode.com/problems/4sum/",
                gfg: "https://www.geeksforgeeks.org/find-four-elements-that-sum-to-a-given-value-set-2/",
            },
            {
                id: 4,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Maximum subarray",
                article: "https://www.geeksforgeeks.org/largest-sum-contiguous-subarray/",
                leetcode: "https://leetcode.com/problems/maximum-subarray/",
                gfg: "https://www.geeksforgeeks.org/largest-sum-contiguous-subarray/",
            },
            {
                id: 5,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Maximum product subarray",
                article: "https://www.geeksforgeeks.org/maximum-product-subarray/",
                leetcode: "https://leetcode.com/problems/maximum-product-subarray/",
                gfg: "https://www.geeksforgeeks.org/maximum-product-subarray/",
            },
            {
                id: 6,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Find minimum in rotated sorted array",
                article: "https://www.geeksforgeeks.org/find-minimum-element-in-a-sorted-and-rotated-array/",
                leetcode: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
                gfg: "https://www.geeksforgeeks.org/find-minimum-element-in-a-sorted-and-rotated-array/",
            },
            {
                id: 7,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Search in rotated sorted array",
                article: "https://www.geeksforgeeks.org/search-an-element-in-a-sorted-and-pivoted-array/",
                leetcode: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
                gfg: "https://www.geeksforgeeks.org/search-an-element-in-a-sorted-and-pivoted-array/",
            },
            {
                id: 8,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Climbing stairs",
                article: "https://www.geeksforgeeks.org/count-ways-reach-nth-stair/",
                leetcode: "https://leetcode.com/problems/climbing-stairs/",
                gfg: "https://www.geeksforgeeks.org/count-ways-reach-nth-stair/",
            },
        ],
        Easy: 3,
        Medium: 5,
        Hard: 2,
        overview: "Lorem ipsum dolor sit amet, consectetur adipisicingelit. Saepe voluptates pariatur sed atque repellat laudantium, ut assumenda excepturi",
        solved: 5,
        totalQues: 10
    },
    {
        id: 15,
        topic: 'Dynamic Programming',
        img: "/Dsaz/Images/dp1.jpg",
        problems: [
            {
                id: 1,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Two sums",
                article: "https://www.geeksforgeeks.org/two-sum-problem/",
                leetcode: "https://leetcode.com/problems/two-sum/",
                gfg: "https://www.geeksforgeeks.org/two-sum/",
            },
            {
                id: 2,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Three sums",
                article: "https://www.geeksforgeeks.org/find-triplets-array-whose-sum-equal-zero/",
                leetcode: "https://leetcode.com/problems/3sum/",
                gfg: "https://www.geeksforgeeks.org/find-triplets-array-whose-sum-equal-zero/",
            },
            {
                id: 3,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Four sums",
                article: "https://www.geeksforgeeks.org/find-four-elements-that-sum-to-a-given-value-set-2/",
                leetcode: "https://leetcode.com/problems/4sum/",
                gfg: "https://www.geeksforgeeks.org/find-four-elements-that-sum-to-a-given-value-set-2/",
            },
            {
                id: 4,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Maximum subarray",
                article: "https://www.geeksforgeeks.org/largest-sum-contiguous-subarray/",
                leetcode: "https://leetcode.com/problems/maximum-subarray/",
                gfg: "https://www.geeksforgeeks.org/largest-sum-contiguous-subarray/",
            },
            {
                id: 5,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Maximum product subarray",
                article: "https://www.geeksforgeeks.org/maximum-product-subarray/",
                leetcode: "https://leetcode.com/problems/maximum-product-subarray/",
                gfg: "https://www.geeksforgeeks.org/maximum-product-subarray/",
            },
            {
                id: 6,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Find minimum in rotated sorted array",
                article: "https://www.geeksforgeeks.org/find-minimum-element-in-a-sorted-and-rotated-array/",
                leetcode: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
                gfg: "https://www.geeksforgeeks.org/find-minimum-element-in-a-sorted-and-rotated-array/",
            },
            {
                id: 7,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Search in rotated sorted array",
                article: "https://www.geeksforgeeks.org/search-an-element-in-a-sorted-and-pivoted-array/",
                leetcode: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
                gfg: "https://www.geeksforgeeks.org/search-an-element-in-a-sorted-and-pivoted-array/",
            },
            {
                id: 8,
                status: "pending",
                isSolved: false,
                type: "Easy",
                question: "Climbing stairs",
                article: "https://www.geeksforgeeks.org/count-ways-reach-nth-stair/",
                leetcode: "https://leetcode.com/problems/climbing-stairs/",
                gfg: "https://www.geeksforgeeks.org/count-ways-reach-nth-stair/",
            },
        ],
        Easy: 3,
        Medium: 5,
        Hard: 2,
        overview: "Lorem ipsum dolor sit amet, consectetur adipisicingelit. Saepe voluptates pariatur sed atque repellat laudantium, ut assumenda excepturi",
        solved: 5,
        totalQues: 10
    }
];